### ISSUE TITLE
haskoin-core-1.2.2 fails to build with crypton-1.1

### ISSUE THREAD

**Issue by juhp** [haskoin/haskoin#424]
```
       Building library for haskoin-core-1.2.2...
       [ 1 of 48] Compiling Haskoin.Address.Bech32
       [ 2 of 48] Compiling Haskoin.Util.Helpers
       [ 3 of 48] Compiling Haskoin.Crypto.Keys.Extended.Internal
       [ 4 of 48] Compiling Haskoin.Util.Marshal
       [ 5 of 48] Compiling Haskoin.Util
       [ 6 of 48] Compiling Haskoin.Script.Common
       [ 7 of 48] Compiling Haskoin.Crypto.Keys.Mnemonic
       [ 8 of 48] Compiling Haskoin.Crypto.Hash
       /home/curators/work/unpack-dir/unpacked/haskoin-core-1.2.2-bf1d30ff60a7c594a3be97aafe31f43d8594277aac3cf11baa00dcba299cb315/src/Haskoin/Crypto/Keys/Mnemonic.hs:112:28: error: [GHC-39999]
           • No instance for ‘BA.ByteArrayAccess
                                (crypton-1.1.4:Crypto.Hash.Types.Digest SHA256)’
               arising from a use of ‘BA.convert’
           • In the first argument of ‘(.)’, namely ‘BA.convert’
             In the second argument of ‘(.)’, namely
               ‘BA.convert . hashWith SHA256’
             In the expression: getBits len . BA.convert . hashWith SHA256
           |
       112 | calcCS len = getBits len . BA.convert . hashWith SHA256
           |                            ^^^^^^^^^^

       /home/curators/work/unpack-dir/unpacked/haskoin-core-1.2.2-bf1d30ff60a7c594a3be97aafe31f43d8594277aac3cf11baa00dcba299cb315/src/Haskoin/Crypto/Hash.hs:195:30: error: [GHC-39999]
           • Could not deduce ‘ByteArrayAccess (Digest SHA512)’
               arising from a use of ‘convert’
             from the context: ByteArrayAccess b
               bound by the type signature for:
                          sha512 :: forall b. ByteArrayAccess b => b -> Hash512
               at src/Haskoin/Crypto/Hash.hs:194:1-45
           • In the first argument of ‘(.)’, namely ‘convert’
             In the second argument of ‘(.)’, namely ‘convert . hashWith SHA512’
             In the second argument of ‘(.)’, namely
               ‘toShort . convert . hashWith SHA512’
           |
       195 | sha512 = Hash512 . toShort . convert . hashWith SHA512
           |                              ^^^^^^^

       /home/curators/work/unpack-dir/unpacked/haskoin-core-1.2.2-bf1d30ff60a7c594a3be97aafe31f43d8594277aac3cf11baa00dcba299cb315/src/Haskoin/Crypto/Hash.hs:195:40: error: [GHC-39999]
           • Could not deduce ‘ram-0.22.0:Data.ByteArray.Types.ByteArrayAccess
                                 b’
               arising from a use of ‘hashWith’
             from the context: ByteArrayAccess b
               bound by the type signature for:
                          sha512 :: forall b. ByteArrayAccess b => b -> Hash512
               at src/Haskoin/Crypto/Hash.hs:194:1-45
             Possible fix:
               add (ram-0.22.0:Data.ByteArray.Types.ByteArrayAccess
                      b) to the context of
                 the type signature for:
                   sha512 :: forall b. ByteArrayAccess b => b -> Hash512
           • In the second argument of ‘(.)’, namely ‘hashWith SHA512’
             In the second argument of ‘(.)’, namely ‘convert . hashWith SHA512’
             In the second argument of ‘(.)’, namely
               ‘toShort . convert . hashWith SHA512’
           |
       195 | sha512 = Hash512 . toShort . convert . hashWith SHA512
           |                                        ^^^^^^^^

       /home/curators/work/unpack-dir/unpacked/haskoin-core-1.2.2-bf1d30ff60a7c594a3be97aafe31f43d8594277aac3cf11baa00dcba299cb315/src/Haskoin/Crypto/Hash.hs:199:30: error: [GHC-39999]
           • Could not deduce ‘ByteArrayAccess (Digest SHA256)’
               arising from a use of ‘convert’
             from the context: ByteArrayAccess b
               bound by the type signature for:
                          sha256 :: forall b. ByteArrayAccess b => b -> Hash256
               at src/Haskoin/Crypto/Hash.hs:198:1-45
           • In the first argument of ‘(.)’, namely ‘convert’
             In the second argument of ‘(.)’, namely ‘convert . hashWith SHA256’
             In the second argument of ‘(.)’, namely
               ‘toShort . convert . hashWith SHA256’
           |
       199 | sha256 = Hash256 . toShort . convert . hashWith SHA256
           |                              ^^^^^^^

```

**Comment by jprupp** [comment]
Fixed.
